# 项目相关配置
admission:
  # 名称
  name: Admission
  # 文件路径 示例（ Windows配置D:/admission/upload，Linux配置 /home/admission/upload）
  profile: D:/admission
uid:
  reserveMinutes: 10080
schedule:
  userfile:
    cron: 0 0/1 * * * ?
spring:
  application:
    name: admission
  #  datasource:
  #    type: com.zaxxer.hikari.HikariDataSource
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://123.57.131.180:13306/spring_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
  #    username: root
  #    password: 123456
  #    hikari:
  #      minimum-idle: 5
  #      idle-timeout: 600000
  #      maximum-pool-size: 10
  #      auto-commit: true
  #      pool-name: MyHikariCP
  #      max-lifetime: 1800000
  #      connection-timeout: 30000
  #      connection-test-query: SELECT 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://123.57.131.180:13306/spring_security?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      # 初始连接数
      initialSize: 8
      # 最小连接池数量
      minIdle: 16
      # 最大连接池数量
      maxActive: 64
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  #redis 配置
  redis:
    database: 0
    host: 123.57.131.180
    port: 16379
    password:
    timeout: 10s
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8666
  servlet:
    context-path: /school

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌有效期（单位秒 默认30分钟） 60 * 30
  expireTime: 1800

file:
  max-rows: 500000

cors:
  allowedOrigin: '*'
  allowedHeaders: '*'
  allowedMethods: GET,PUT,POST,PATCH,DELETE,OPTIONS

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml, classpath:mybatis/mapping/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.spring.**
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    # meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    #root: warn
    com.admission.security.dao: debug